### ISSUE TITLE
Broken Link to the Securing-Elmah Code Sample

### ISSUE THREAD

**Issue by jasel-lewis** [haacked/haacked.com#1037]
Searched the Git-Hub repo before posting in case I could just create a PR with the found sample code, but alas, could not find it.

The [Securely Implement ELMAH For Plug And Play Error Logging](https://haacked.com/archive/2007/07/24/securely-implement-elmah-for-plug-and-play-error-logging.aspx/) blog post has a link to download demo code.  This link is [broken again](https://github.com/haacked/haacked.com/issues/32).  :(

The code for the post is [located here](https://github.com/haacked/haacked.com/blob/master/_posts/archived/2007/2007-07-24-securely-implement-elmah-for-plug-and-play-error-logging.aspx.markdown) on Git-Hub.

Please and thank you and, Happy Birthday (belated), @haacked!

**Comment by haacked** [comment]
@jasel-lewis I just deployed a fix, should be up soon. Thanks for the belated birthday wishes!
