### ISSUE TITLE
Post idea comparison of languages for open source.

### ISSUE THREAD

**Issue by raystorm** [Haacked/haacked.com#104]
You write a lot about .Net in your posts, it seems like that's where you primarily program. Git Hub pages are Jekyll which is ruby. From some of your other Powys it seems like you've worked other language and OSS. I'm curious. How do the available libraries(ORM, IoC, Di, web frameworks, etc) and tools(code coverage, package management, builds, etc) compare for the open source crowd for .Bet and other languages, say Java, JavaScript, or even PHP?

Thank you for your attention and consideration.

**Comment by Haacked** [comment]
This is an interesting topic, but I don't feel I have enough experience with these other platforms to cover the differences well.
