### ISSUE TITLE
Fix Tag links

### ISSUE THREAD

**Issue by aribakker** [Haacked/haacked.com#109]
Tried to access the above URL from the following page on MSDN: http://msdn.microsoft.com/en-us/library/gg416514(v=vs.108).aspx

**Comment by Haacked** [comment]
I need to implement a Jekyll solution to tags and then go back and fix up all the tags. Unfortunately, GitHub Pages doesn't yet support a Tags plug-in.

**Comment by Haacked** [comment]
I'll track this in #71
