### ISSUE TITLE
Link to: Split Pascal/Camel Cased Strings 404

### ISSUE THREAD

**Issue by futureturnip** [Haacked/haacked.com#145]
Phil, You Asked Us to Log Issues with 404 Links on Your Blog,

The 404 link is: 
http://haacked.com/archive/2005/09/24/10334.aspx

Seems like it should go here:
http://haacked.com/archive/2005/09/23/splitting-pascalcamel-cased-strings.aspx/

I was coming from here: http://weblogs.asp.net/jongalloway/426087

Cheers,

Jeff.

**Comment by Haacked** [comment]
smart ass. I fixed the old URL to redirect to the new one too. :smile:
