### ISSUE TITLE
Disqus Update email has old paths?

### ISSUE THREAD

**Issue by michaeldevenney** [Haacked/haacked.com#151]
I get an update email from Disqus each week or anytime someone I follow joins a discussion.  Since your 104 page asks us to log issues, here it is.  I clicked on the "View on You've been Haacked" link and it 104'ed on me.  I'll try to figure out what the link below resolves to...
http://redirect.disqus.com/url?threadrank=1&impression=2c22c98c-3833-11e4-a33e-002590852c3c&forum=2103057&thread=2927915057&url=http%3A%2F%2Fhaacked.com%2Farchive%2F2014%2F08%2F14%2Fpay-for-performance%2F%23comment-1579392870%3A05xq2P7xF0vSrM4elAcPyostJGE&postrank=1&variant=active&experiment=digests&role=post-comment-footer&behavior=click&post=1579392870&type=digest.daily&event=email

Thanks, 
Mike Devenney

**Comment by Haacked** [comment]
Thanks! I need to look into how Disqus handles these. I haven't figured out how to correct them.
