### ISSUE TITLE
Edit link not working

### ISSUE THREAD

**Issue by SeanKilleen** [haacked/haacked.com#1579]
Take for example the recent post on C# and Stripe.

URL is: https://haacked.com/archive/2022/10/12/calculating-mrr-with-stripe-and-csharp/

But the suggest edit link refers to `https://github.com/haacked/haacked.com/edit/main/_posts/2022/2022-10-12-calculating-mrr-with-stripe-and-csharp.md`

Which 404s.

**Comment by SeanKilleen** [comment]
Taking a look at this real quick to see if I can do a drive-by PR on it.

**Comment by SeanKilleen** [comment]
Update : it wasn't a 404. For some reason the editing experience is returning a 500 error clicking edit when I'm at https://github.com/haacked/haacked.com/blob/main/_posts/2022/2022-10-12-calculating-mrr-with-stripe-and-csharp.md -- so it seems like something else is going on here, but the URL isn't wrong.

**Comment by haacked** [comment]
Works for me. Maybe a temporary GitHub issue?

**Comment by SeanKilleen** [comment]
Perhaps just an issue for me.

> ![image](https://user-images.githubusercontent.com/2148318/195643198-e7d03c09-9f71-47d8-b043-61d919d16d7b.png)

Goes to <https://github.com/haacked/haacked.com/edit/main/_posts/2022/2022-10-12-calculating-mrr-with-stripe-and-csharp.md>

> ![image](https://user-images.githubusercontent.com/2148318/195643310-a8e904b6-15a9-4046-87e8-2449fb8352f8.png)

Odd. I'll close this for now since it's not a real issue.

**Comment by haacked** [comment]
Try it in an incognito browser.

**Comment by SeanKilleen** [comment]
Same result. See the page, login, click edit, 500 error. 🤔 Haven't seen that before. Oh well, is what it is.
