### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by SergeantJack** [Haacked/haacked.com#162]
Hi,
I found a broken link. The resulting 404 page asked me to log it:

Requested Url: http://haacked.com/archive/2005/06/11/simulating_httpContext.aspx/
Referred From: http://haacked.com/archive/2007/06/19/unit-tests-web-code-without-a-web-server-using-httpsimulator.aspx/

Hope this helps!

**Comment by Haacked** [comment]
Thanks! I fixed the link and it should update shortly.
