### ISSUE TITLE
Found a 404

### ISSUE THREAD

**Issue by phuzi** [Haacked/haacked.com#168]
Logging an error as requested by the site...

I was trying to access the following link:

http://haacked.com/archive/2009/12/11/localizing-aspnetmvc-validation.aspx

Following a link from the page at:

http://forums.asp.net/t/1840464.aspx?using+resource+files+resx+in+DataAnnotations+ValidationAttribute

**Comment by Haacked** [comment]
Thanks! I pushed a redirect which should fix this.
