### ISSUE TITLE
Bad practise for sharing a post

### ISSUE THREAD

**Issue by NicoJuicy** [Haacked/haacked.com#178]
Sharing your site gives "You've been haacked" instead of a decent title of the blog post (not very descriptive if you want any content to be shared )

Mentioned here: https://news.ycombinator.com/item?id=9250401

**Comment by Haacked** [comment]
Shame on me! Interested in submitting a PR or giving me a suggestion for what exactly I should change? If not, I'll figure it out. Just always looking for people to add to my [contributors list](http://haacked.com/contributors/)  :smile:

**Comment by NicoJuicy** [comment]
Well, don't know Yekyll. But the pages do look for a page.head ( see includes/head.html ) and when i look at a custom post it has some variables. I suggest to use the variable page.title next to post.title (if possible) or change the head.html to 

<title>{% if page.title %}{{ page.title }} - {% elsif post.title %}{{ post.title }} - {% endif %}{{ site.title }}</title>

Just my 2 cents though, can't run it here... 

;)

**Comment by Haacked** [comment]
Fixed by d2449b3af0dbe0a15b2fa63f3e83a0e82e65f97b

Thanks for the suggestion!

![coffee-thumbsup](https://cloud.githubusercontent.com/assets/19977/6793430/746ee6ac-d181-11e4-8b75-c7ccb7ea79ba.gif)

**Comment by NicoJuicy** [comment]
Haha, awesome Phil! I have been following your blog a long time (now and then), being a .Net programmer (mostly, not solely) and you as a Microsoft evangelist (previously)...

So this just makes me smile! :-P 

Good day!

**Comment by Haacked** [comment]
@NicoJuicy awesome! Glad to have you as a long time reader.

> and you as a Microsoft evangelist (previously)

Just to be clear, I was never an evangelist. :smile: I was a Program Manager over there.

**Comment by NicoJuicy** [comment]
Ah well, together with Scott and Scott, you three were the only ones i was really following. So actually, you kinda was :P

**Comment by Haacked** [comment]
Fair enough. :smile:
