### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Emwat** [Haacked/haacked.com#186]
Was on http://haacked.com/archive/2011/01/06/razor-syntax-quick-reference.aspx/
Under the Comments header, there's a "You've Been Haacked" link.
Left side dims, right side pulls up a column ala Tumblr style.

Clicked on this link and got an error message.
http://haacked.com/archive/2014/08/14/pay-for-performance%20-%20Copy/

**Comment by Haacked** [comment]
Screenshot? I can't find it.

**Comment by Emwat** [comment]
![capture](https://cloud.githubusercontent.com/assets/3729027/6879562/20d68646-d4d1-11e4-929f-a0fdf4a91176.PNG)

![capture1](https://cloud.githubusercontent.com/assets/3729027/6879563/2bfa6790-d4d1-11e4-951e-c488ca9667fd.PNG)

**Comment by Haacked** [comment]
Oh! I didn't even know that was there. it's a Disqus feature and I can't figure out how to fix it. :frowning:
