### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DanDigiDash** [Haacked/haacked.com#188]
I've found a broken link I'd really like to get to for more info.
http://haacked.com/archive/2005/03/07/2317.aspx
I've got there from 
http://haacked.com/archive/2006/01/13/SettingUpLog4NetForMultiLayeredApplications.aspx/
Article title: Setting Up Log4Net For Multi Layered Applications
Date:  January 13, 2006

**Comment by Haacked** [comment]
Thanks for the report. I fixed the link. It should point to http://haacked.com/archive/2005/03/07/ConfiguringLog4NetForWebApplications.aspx/
