### ISSUE TITLE
missing link 404

### ISSUE THREAD

**Issue by razvanmatei** [Haacked/haacked.com#214]
http://haacked.com/archive/2005/01/20/1967.aspx

**Comment by Haacked** [comment]
Where did you find the link? Do you recall what it was supposed to link to?

**Comment by razvanmatei** [comment]
I don't remember exactly, but I was looking on your website for some neural networks code or tutorial, and when I thought I found something interesting the link was broken....So I reported broken link. Sorry if it doesn't help.

**Comment by Haacked** [comment]
I figured it out. It should have linked to http://haacked.com/archive/2005/01/20/Image_Based_CAPTCHA_Losing_Appeal.aspx/

I pushed a redirect that should be in effect soon. Thanks!
