### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by TiagoPT** [Haacked/haacked.com#219]
Hi, as you requested:
* [URL](http://haacked.com/archive/2005/03/13/2357.aspx) I'm trying to reach
* Found the URL in ["I've avoided the incestuous nature of **blogging about blogging**..."](http://blog.codinghorror.com/blogging-about-blogging/)

**Comment by Haacked** [comment]
Thanks for the report! I pushed a fix. It should take a moment to propagate. Here's the URL I've added a redirect to: http://haacked.com/archive/2005/03/13/Blogging-About-Blogging-AboutBlogging.aspx/
