### ISSUE TITLE
Dead link HttpWebRequest and the Expect: 100-continue Header Problem 

### ISSUE THREAD

**Issue by srijken** [Haacked/haacked.com#226]
Incoming link was found at: http://geekswithblogs.net/mnf/archive/2006/09/13/91012.aspx
Broken link is: http://haacked.com/archive/2004/05/15/449.aspx
Should be: http://haacked.com/archive/2004/05/15/http-web-request-expect-100-continue.aspx/

Thanks!

**Comment by Haacked** [comment]
Thanks for the report! I added a redirect to fix it.
