### ISSUE TITLE
Broken links for tags

### ISSUE THREAD

**Issue by tylerbhughes** [Haacked/haacked.com#232]
Per your request on your error 404 page, I'd like to report that the tags for your blog posts are not working. I was on this [blog post](http://haacked.com/archive/2012/01/02/structuring-unit-tests.aspx/) and I tried both the unit testing and the tdd tags but both of them directed me to the 404 page.

**Comment by Haacked** [comment]
Yeah, all my tag posts are broken. Closing as a dupe of #71
