### ISSUE TITLE
Unable to reach http://haacked.com/archive/2007/04/20/write-readable-code-by-making-its-intentions-clear.aspx

### ISSUE THREAD

**Issue by Natalia-Muray** [Haacked/haacked.com#239]
I found the link in this article https://blogs.msdn.microsoft.com/ericlippert/2007/04/23/write-only-variables-considered-harmful-or-beneficial/

**Comment by Haacked** [comment]
Thanks for the report! I pushed a fix and it should be live soon. :smile:
