### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by rondakay** [Haacked/haacked.com#256]
http://haacked.com/archive/0001/01/01/take-charge-of-your-security.aspx

**Comment by Haacked** [comment]
Thanks! Where did you find that link?

**Comment by rondakay** [comment]
I believe I searched MVC security.

Thanks

Ronda Pederson 

-----Original Message-----

**Comment by Haacked** [comment]
Here's the actual link that should point to. http://haacked.com/archive/2009/02/07/take-charge-of-your-security.aspx/

I'll see if I can find where this link was posted.
