### ISSUE TITLE
it does not work with [ComplexType]

### ISSUE THREAD

**Issue by mmmahdavimanesh** [Haacked/haacked.com#262]
hi there:

thanks for your nice code for . but the code does not work with ComplexType.
I declare a Dimension ComplexType but i Cannot add insert my custrom display attribute for it
 http://haacked.com/archive/2011/07/14/model-metadata-and-validation-localization-using-conventions.aspx/

**Comment by Haacked** [comment]
Hi @mmmahdavimanesh could you log a detailed issue on the GitHub repo? https://github.com/Haacked/mvc-metadata-conventions
