### ISSUE TITLE
Unable to find link to 'There is no perfect design'

### ISSUE THREAD

**Issue by arpitjain1821** [Haacked/haacked.com#269]
Broken Link: http://haacked.com/archive/2005/05/31/ThereIsNoPerfectDesign.aspx
Source: http://haacked.com/archive/2007/12/11/favor-composition-over-inheritance-and-other-pithy-catch-phrases.aspx/

**Comment by Haacked** [comment]
Ok, the correct link is: http://haacked.com/archive/2005/05/30/thereisnoperfectdesign.aspx/

I'll fix this up.
