### ISSUE TITLE
Received 404 on Testing Routes link

### ISSUE THREAD

**Issue by mbowman8** [Haacked/haacked.com#273]
Hello Phil,

I was attempting to navigate from http://stackoverflow.com/questions/9220990/unit-testing-asp-net-mvc-4-apps-thoroughly to http://haacked.com/archive/2007/12/16/testing-routes-in-asp.net-mvc.aspx/%7B and received a 404. I'll attempt to find the relocated page through other means.

Thanks,
Michael

**Comment by mbowman8** [comment]
Looks like the link should be http://haacked.com/archive/2007/12/17/testing-routes-in-asp.net-mvc.aspx/ (a slight date change)

**Comment by Haacked** [comment]
Thanks! I fixed the link on SO.
