### ISSUE TITLE
Invalid link on StackOverflow

### ISSUE THREAD

**Issue by antonti** [Haacked/haacked.com#274]
This is the link: http://haacked.com/archive/2009/03/03/aspnetmvc-changes-for-rc2.aspx
This is the SO thread where it was referenced: http://stackoverflow.com/questions/524936/how-to-maintain-state-of-html-checkbox-in-asp-net-mvc

**Comment by Haacked** [comment]
I think I was missing a redirect. Seems to be fixed now.
