### ISSUE TITLE
Broken link to http://haacked.com/archive/2005/10/13/Remote_Desktop_To_Console_Session.aspx

### ISSUE THREAD

**Issue by barbeque** [Haacked/haacked.com#283]
Was heading to:

http://haacked.com/archive/2005/10/13/Remote_Desktop_To_Console_Session.aspx

from the "Related Posts" section of 

http://haacked.com/archive/2006/10/16/Remote_Desktop_On_A_NonStandard_Port.aspx/

The other link on that "Related Posts" section is also broken, but it's from a different blog so not sure you can find the new source:

http://stevenharman.net/Mapping_Drives_via_Remote_Desktop

Have a good one! Thanks for the blog.

**Comment by Haacked** [comment]
Thanks! I've updated the posts. It might take a small while to propagate.
