### ISSUE TITLE
MSTSC Trick Link Broken

### ISSUE THREAD

**Issue by rmegal** [Haacked/haacked.com#286]
This showed up in feedly today: [http://haacked.com/archive/2017/08/31/2005-10-13-remote_desktop_to_console_session.aspx/](http://haacked.com/archive/2017/08/31/2005-10-13-remote_desktop_to_console_session.aspx/) I'm guessing it is an update to a post from 2005 and it got lost in the update.

We use RDP all of the time at work and I occasionally run into the two-session limit. This is handy.

Thanks,

Ray

**Comment by Haacked** [comment]
Weird. Where's the link from? Here's where it's supposed to link to: http://haacked.com/archive/2005/10/13/remote_desktop_to_console_session.aspx/

**Comment by rmegal** [comment]
It is in my Feedly feed for your site. Something is goofy but I'm guessing it has more to do with Feedly and not your site. The VISIT WEBSITE link is the invalid one. Thanks for the follow-up.
![image](https://user-images.githubusercontent.com/213904/30230421-f3c533e6-9481-11e7-92df-e26bd3937cb0.png)

**Comment by Haacked** [comment]
No problem. I had done something wrong that caused the post to appear again, but the URL shouldn't have been broken regardless. But all should be fixed now. :smile:
