### ISSUE TITLE
ConfigurationSolution code is not valid

### ISSUE THREAD

**Issue by vfrank66** [Haacked/haacked.com#305]
The archive file in https://github.com/Haacked/haacked.com/blob/gh-pages/code/Haack.ConfigurationSolution.zip is not a valid archive file.

**Comment by Haacked** [comment]
Where'd you find the link to that file?

**Comment by Haacked** [comment]
That zip file is corrupted. However, I wouldn't recommend that solution any more. Use https://haacked.com/archive/2007/03/12/custom-configuration-sections-in-3-easy-steps.aspx instead.

**Comment by vfrank66** [comment]
Thank you!
