### ISSUE TITLE
Add RSS tag to header?

### ISSUE THREAD

**Issue by fidelisrafael** [Haacked/haacked.com#307]
Hi @Haacked, what's up?

Your blog is awesome! I want to follow your posts by RSS...I'm using the "Feedly" extension that automatically searchs for RSS alternate tag in HTML Markup, looks like you have a `<a>` tag in footer with the RSS link(or had, I can spot in HTML but I can't see in page), may I suggest that you add:

```
<link rel="alternate" type="application/rss+xml" title="You’ve Been Haacked" href="http://feeds.haacked.com/haacked">
```
This way robots can index your blog in a more effective way! Thsnks

**Comment by Haacked** [comment]
I already have

```
<link href="http://feeds.haacked.com/haacked" rel="alternate" title="You've Been Haacked" type="application/atom+xml">
```

Are robots not finding that?

**Comment by Haacked** [comment]
Supposedly Feedly support atom feeds.

**Comment by fidelisrafael** [comment]
Wow, good, I missed this!
