### ISSUE TITLE
Typo in "Comments for Jekyll Blogs" post

### ISSUE THREAD

**Issue by NikZar** [Haacked/haacked.com#353]
Hi, first of all I'd like to thank you for all the great content.

I just want you to fix a typo in the Comment Spam section of the "Comments for Jekyll Blogs" post.
"That would simply require that I change the Azure funcTion." the last phrase is missing a T.

Idk if it is the right way to report it, hopefully this helps.

**Comment by Haacked** [comment]
> Hi, first of all I'd like to thank you for all the great content.

Thanks @NikZar!

> I just want you to fix a typo in the Comment Spam section

Thanks for reporting a typo. If you'd like to fix it yourself, each of my blog posts have a "Suggest Edit" link. For example, that blog post's [suggest edit link goes here](https://github.com/Haacked/haacked.com/edit/gh-pages/_posts/2018/2018-06-24-comments-for-jekyll-blogs.markdown).

It'll fork my repo and bring up the in-browser editor. You can make your fix and create a commit and Pull Request. The nice thing about that is when I merge your PR, you show up in my list of contributors: https://haacked.com/contributors/

**Comment by Haacked** [comment]
If you'd rather not, I can just fix it. :smile: Some folks like adding to their contribution graph.

**Comment by NikZar** [comment]
Done, hopefully you received the pull request :)
