### ISSUE TITLE
Blog home page renders like a mobile page on Firefox desktop

### ISSUE THREAD

**Issue by davecarpie** [Haacked/haacked.com#585]
Screenshots taken on Surface Book Pro 2 monitor. Firefox 64.0. Site rendered as expected in Chrome

![image](https://user-images.githubusercontent.com/8252239/50190481-489d0480-038e-11e9-8491-1cb7e5ebd20d.png)

![image](https://user-images.githubusercontent.com/8252239/50190541-7e41ed80-038e-11e9-8b8d-b674a5603836.png)

**Comment by Haacked** [comment]
Wow. What resolution is your monitor?

**Comment by davecarpie** [comment]
3000 x 2000 
https://www.sizescreens.com/microsoft-surface-book-2-screen-specifications/

**Comment by Haacked** [comment]
Hmm, I just tried this with Firefox 64 on a Mac and it renders fine. I'll have to try it on Windows. Is your window fully expanded. If you shrink the browser horizontally far enough, it will trigger the mobile view.

**Comment by davecarpie** [comment]
Well this is embarrassing. Looking at the screenshot my browser shows that its at 220% zoom. I don't know how it got that far zoomed in only on your site but when I reset it it went back to normal.

Sorry!

**Comment by Haacked** [comment]
LOL! Happens to the best of us. No worries. Thanks for following up!
