### ISSUE TITLE
Blog idea: Is .NET moving to js?

### ISSUE THREAD

**Issue by distantcam** [Haacked/haacked.com#95]
Lately I've been seeing a lot of .NET developers and .NET talks talking about everything except .NET. Node.js, jquery, css, rxjava.

Have we as .NET developers been forced to move onto other technologies? And why are most of these web technologies? Is the desktop dead?

**Comment by Haacked** [comment]
Great idea, but at this point with .NET core I think the it's pretty clear the answer is "No."
