### ISSUE TITLE
Post Idea: Successful OSS in .NET

### ISSUE THREAD

**Issue by George-Collins** [Haacked/haacked.com#97]
I know you've written about this in the past, but Mr Miller is apparently hanging up his Fubu boots. Reasons cited include the struggle to gain traction for the project, and having all the responsibility on too few people.
Does this chime with your own work-funk?
Do you have any insights into the 'architecture of participation' with that project that could have helped?

**Comment by Haacked** [comment]
Thanks for the suggestion, sorry I didn't get around to it. Jeremy has more experience than most running a .NET OSS project. I think there's a lot of luck involved. If your project catches lightning in a bottle and a lot of people jump in to participate, then great.

But most projects are ignored. If they continue to serve a need you have, this usually isn't a big problem. but if you no longer need the project and maintain it out of obligation, that's a recipe for burnout.
