### ISSUE TITLE
How to write a good technical blog post.

### ISSUE THREAD

**Issue by SchalkVersteeg** [Haacked/haacked.com#99]
Hi Phil,
Can you write a post on with pointers and guidelines on how to write a good informative Technical Blog Post.

Some questions I do have is
How to Transform an idea into a good post?
What is the process of planning a post and writing example code?
How long do you normally take to write a post?

Regards
Schalk

**Comment by Haacked** [comment]
I think this post does a good job of it already.

https://medium.freecodecamp.org/how-to-write-a-great-technical-blog-post-414c414b67f6
