### ISSUE TITLE
Comments in email addresses

### ISSUE THREAD

**Issue by Timeroot** [haacked/haacked.com#998]
I enjoyed your blog post, https://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/

You might not have known that RFC2822 allows comments inside email addresses, see for instance https://stackoverflow.com/questions/24973086/are-comments-allowed-in-email-address-domain-part . You could argue that this isn't technically a bug in your regex, because the user could be asked to enter their email address without the comments when registering on a website.

But if, say, you were building an email client, or something that will forward emails from one place to another -- basically anything that will be asked to send an email to an arbitrary valid address -- it really should support those comments. This is a huge kicker, because when accounting for comments, _the set of valid email addresses is not a regular language._ I had to let that sink in for a moment when I realized.

You see, comments are indicated by matching parentheses, and they can be nested. So

`john(my friend and his dad (who goes by james doe)).doe@gmail.com`

is a valid email address, but

`john((my friend and his dad (who goes by james doe)).doe@gmail.com`

is not, because the parentheses are not matched. And while matching parentheses can be recognized by CFGs, they are not a regular language, and can't be recognized by a "true" regular expression.

In practice, many languages have extensions to their regular expression engine that allow recursion or other constructs in a way that allows you to recognize correctly matched parentheses. See for instance https://stackoverflow.com/questions/546433/regular-expression-to-match-balanced-parentheses

So as a bottom line, you can probably write a regex to match valid email addresses, but you won't be able to do this is any kind of language-independent way, because it will depend on unique extensions.

**Comment by haacked** [comment]
@Timeroot Those are great examples. I did learn that after I wrote that post. I wrote a follow-up post a while back where I suggested to be very liberal with what email addresses you accept:
https://haacked.com/archive/2007/08/26/dont-be-a-validation-nazi.aspx/

At this point, my recommendation for email validation is to send a verification email to the given address. That's pretty much the only sure way to know if you have a real email address.
